Scene tools
PurdueSIGGD/ProjectW pull request #16
Opened 2018-03-30 00:18 UTC by TheNerdv2

Added Healthpacks, Jumpads and associated prefabs. Added prefabs to testscene in a haphazardly manner. Healthpacks don't update between players, if one player takes one, that doesn't happen for another player.

2018-03-30 01:22 UTC, Lonswaya requested changes
Next meeting, please make a build of this and we can all give it a shot. I have a few behaviors that I want to test.

2018-03-30 01:22 UTC, Lonswaya commented on Assets/Scenes/TestScene.unity
> -    m_PVRFilterTypeDirect: 0
Please pull the latest version of this scene from master and make your changes from there, this will be very hard to resolve the conflict manually.

2018-03-30 01:22 UTC, Lonswaya commented on Assets/C#/World/HealthPack.cs
> +﻿using System.Collections;
Have you tested this across the network, with multiple players? I know we had an issue with players grabbing it at different times, like a player joining a server late.

2018-03-30 01:22 UTC, Lonswaya commented on Assets/C#/World/JumpPad.cs
> +    void OnTriggerEnter(Collider col)
Consider adding a cooldown to this, on a per-player basis. Imagine if a player accidentally hits it twice with two different hitboxes, they would go flying. Or you could just use the collider layer that the player's capsule is on.

Also this may get terrifying if players ragdoll on this trampoline..

2018-04-19 23:17 UTC, TheNerdv2 commented
Updated Jump pad to launch you when you move into it, we should be go for merge.

2018-04-20 15:36 UTC, Lonswaya commented
I made some changes to have the health packs work across networks, so it isnt all clientside. Should work better now.

Later we should take a look at jump pads, because sometimes just standing on them leads to inconsistent results, but it works for now.

2018-04-20 15:36 UTC, Lonswaya approved these changes

2018-04-20 15:38 UTC, merged